service: serverless

provider:
  name: aws
  runtime: nodejs8.10
  region: us-west-1
  stage: dev

plugins:
  - serverless-offline

functions:
  weather:
    handler: src/api/weather.handler
    events:
      - http: GET /weather

  todos:
    handler: src/api/todos.handler
    events:
      - http: GET /todos

  todo:
    handler: src/api/todo.handler
    events:
      - http:
          path: todos/{id}
          method: get
          request:
            parameters:
              paths:
                id: true
