service: serverless

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  stage: dev

plugins:
  - serverless-offline

functions:
  api:
    handler: src/api/api.handler
    events:
      - http: ANY /
      - http: 'ANY /echo/{params}'

